name: "Auto assignment for issues"

on:
  issues:
    types: ["opened"]

jobs:
  auto-assign:
    uses: "tinted-theming/home/.github/workflows/shared-auto-assign-issues.yml@stable-actions"
    secrets:
      token: ${{ secrets.BOT_ACCESS_TOKEN }}
